// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Rating,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  userId: __t.identity().name("user_id"),
  longitude: __t.f64(),
  latitude: __t.f64(),
  get rating() {
    return Rating;
  },
  createdAt: __t.timestamp().name("created_at"),
});
