// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const User = __t.object("User", {
  identity: __t.identity(),
  username: __t.string(),
  email: __t.string(),
  registered: __t.bool(),
  createdAt: __t.timestamp(),
  modifiedAt: __t.timestamp(),
});
export type User = __Infer<typeof User>;

