// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ChangeUserInfoReducer from "../change_user_info_reducer";
import RegisterUserReducer from "../register_user_reducer";

export type ChangeUserInfoParams = __Infer<typeof ChangeUserInfoReducer>;
export type RegisterUserParams = __Infer<typeof RegisterUserReducer>;

